.PHONY: clean All

All:
	@echo "----------Building project:[ DefaultProjectForCodelite - Debug ]----------"
	@cd "DefaultProjectForCodelite" && "$(MAKE)" -f  "DefaultProjectForCodelite.mk"
clean:
	@echo "----------Cleaning project:[ DefaultProjectForCodelite - Debug ]----------"
	@cd "DefaultProjectForCodelite" && "$(MAKE)" -f  "DefaultProjectForCodelite.mk" clean
